### ISSUE TITLE
Creating Template with DARTEL fails

### ISSUE THREAD

**Issue by nikinbaidarr** [spm/spm#1]
I segmented a bunch of MR images in spm. When trying to create a template in DARTEL, I cannot select multiple files for some reason. I am getting this error messages:

> invalid dot name structure assignment because the structure array is empty.  Specify a subscript on the 
> structure array to resolve.
>
> /path/to/spm12-r7771/toolbox/DARTEL/spm_dartel_template.m" (v7182), function "spm_dartel_template" at 
> line 49..

I can create templates if I specify only a single file on single and/or multiple image channels. I highly doubt this is an OS specific issue but I'll leave my runtime env here:
```
OS: Arch Linux x86_64
Kernel: 5.16.0-arch1-1
```

Plus I am using spm on GNU Octave and compiled it from the instructions I found [here](https://en.m.wikibooks.org/wiki/SPM/Octave).

**Comment by gllmflndn** [comment]
Hi Nikin,

Thank you for opening the first issue in this brand new repository. The error you observe is probably specific to Octave in the context of arrays of objects: Which version of Octave are you using?

**Comment by nikinbaidarr** [comment]
> Which version of Octave are you using?

Hi!
Here's the output of `octave --version`


```GNU Octave, version 6.4.0
Copyright (C) 2021 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
```

**Comment by gllmflndn** [comment]
Thank you, you're up to date! Perhaps the easiest would be if you could add a line:
```
save dartel.mat -v6
```
just above l.49 in [`spm_dartel_template.m`](https://github.com/spm/spm/blob/main/toolbox/DARTEL/spm_dartel_template.m#L49) and attach here the file `dartel.mat` after the error occurred.

**Comment by gllmflndn** [comment]
I could reproduce it at the second attempt. One temporary solution is to break the assignment in two by replacing l.49:
```matlab
NU(i).dat.fname = fullfile(pth,['u_' nam '_' tname '.nii']);
```
with
```matlab
dat = NU(i).dat;
dat.fname = fullfile(pth,['u_' nam '_' tname '.nii']);
NU(i).dat = dat;
```
Does this solve the issue for you?
I have an open bug report on Octave about this - let me check the status.

**Comment by nikinbaidarr** [comment]
Yes that sort of did it.

Although I had to change a few more lines of code:

```
    if ~isempty(tname),
        NU(i).dat.fname = fullfile(pth,['u_' nam '_' tname '.nii']);
    else
        NU(i).dat.fname = fullfile(pth,['u_' nam '.nii']);
    end
    NU(i).dat.dim   = [dm 1 3];
    NU(i).dat.dtype = 'float32-le';
    NU(i).dat.scl_slope = 1;
    NU(i).dat.scl_inter = 0;
    NU(i).descrip = 'Flow Field';
```

was changed to 

```
    if ~isempty(tname),
        dat = NU(i).dat;
        dat.fname = fullfile(pth,['u_' nam '_' tname '.nii']);
        NU(i).dat = dat;
    else
        dat = NU(i).dat;
        dat.fname = fullfile(pth,['u_' nam  '.nii']);
        NU(i).dat = dat;
    end
    dat = NU(i).dat;
    dat.dim = [dm 1 3];
    NU(i).dat = dat;

    dat = NU(i).dat;
    dat.dtype = 'float32-le';
    NU(i).dat = dat;

    dat = NU(i).dat;
    dat.scl_slope = 1;
    NU(i).dat = dat;

    dat = NU(i).dat;
    dat.scl_inter = 0;
    NU(i).dat = dat;

    NU(i).descrip = 'Flow Field';
```

Thank you for your time. I really appreciate. Should I go on and file a pull request? Also, while we're at it I get a warning when I add the spm dir to my path. 

> warning: /path/tooctave/spm12-r7771/gui_mainfcn.m shadows a core library function

Although applying a few mods to the function and the file name fixed the issue. Also grepped other files to check for dependencies. Thank you once again! I am closing this now.

**Comment by gllmflndn** [comment]
Thank you. Yes, the workaround needs to be applied each time the pattern is used. It seems to be a regression in Octave as it works with 5.2.0 so I will chase up the issue upstream in the hope it will be fixed in the soon-to-be-released 7.1.

`gui_mainfcn.m` is added in the [patch for Octave](https://github.com/spm/spm-docker/blob/main/octave/spm12_r7771.patch#L22) but has now been [included in Octave](https://hg.savannah.gnu.org/hgweb/octave/rev/78435ddc9f88) so you can just delete the file if using a version of Octave that already contains the new function.

**Comment by tiborauer** [comment]
Thank you for the workaround! I wonder whether it could be simplified to this:

```matlab
    dat = NU(i).dat;
    if ~isempty(tname),
        dat.fname = fullfile(pth,['u_' nam '_' tname '.nii']);
    else
        dat.fname = fullfile(pth,['u_' nam '.nii']);
    end
    dat.dim   = [dm 1 3];
    dat.dtype = 'float32-le';
    dat.scl_slope = 1;
    dat.scl_inter = 0;
    descrip = 'Flow Field';

    NU(i).dat = dat;
```

**Comment by gllmflndn** [comment]
Yes, the workaround is to get rid of the chained assignments and the `dat` structure can be defined in one go. An Octave bug report is opened [here](https://savannah.gnu.org/bugs/?61843).

**Comment by tiborauer** [comment]
Thanks! Can we do anything to increase the visibility/priority of the issue?

**Comment by gllmflndn** [comment]
[OO support in Octave](https://wiki.octave.org/Classdef) is incomplete. If I remember correctly, the issue discussed here in the context of array of objects appeared in several bug reports. A first step would be to isolate the changeset that introduced the regression.

I prefer to get the issue fixed upstream rather than adding a temporary workaround in SPM but if it's blocking and unlikely to be resolved anytime soon then we could make an exception (as e.g. [here](https://github.com/spm/spm/commit/2ece5ad47075965c26777207ee0e04cbd8b98d53#diff-b447a94181de9d85f282bac00744ab37c32ab210f42dab24d0e68b76de14c0d9)).
