### ISSUE TITLE
spm_copy, copy jsons when unzipping nifti files

### ISSUE THREAD

**Issue by SRSteinkamp** [spm/spm#10]
Dear all,

the [spm wikibook](https://en.wikibooks.org/wiki/SPM/BIDS), has an example for using `spm_copy` showcasing, that it can do unzipping and copies the accompanying meta-data with it.

```matlab
spm_copy('sub-2475376_task-rest_bold.nii.gz','/derivatives', 'nifti',true, 'gunzip',true)
```

That is in fact not what is happening, as in `spm_copy` lines 69-72

```matlab
        elseif strcmp(spm_file(source{i},'ext'),'nii') 
            sts = copyfile(spm_file(source{i},'ext','mat'), dest{i}, opts.mode{:});
            sts = copyfile(spm_file(source{i},'ext','json'), dest{i}, opts.mode{:});
        end
```

.json and .mat files are only copied, when the source image is a .nii (or .img) file. 

I think adjusting the spm_copy function to match the documentation would be helpful. 

Happy to makae a pull-request, but would appreciate some pointers as it would be necessary two remove both .nii and .gz from the file name to copy the metadata. 

Best wishes!

**Comment by gllmflndn** [comment]
Hi @SRSteinkamp 

Thank you for this - you're right, the code is not behaving as documented.

I was not sure of a clean way to deal with this but I just pushed a change in `spm_copy`. Could you check whether it works correctly for you now? One of the issues is that a sidecar `.json` might contain references to filenames which will become broken if NIfTI files are gunzipped.

You are welcome to open a pull request if you have further changes to this function.

**Comment by gllmflndn** [comment]
Hopefully https://github.com/spm/spm/commit/6bc0c6ac9ae8bd97f0a049d5d7991eb4dfbbe024 fixes the issue so I am going to close this issue as fixed. If it still doesn't work for you or if you have another related issue please open a new issue. Thanks!
