### ISSUE TITLE
Trouble with NaN duration of fMRI event.

### ISSUE THREAD

**Issue by ChristophePhillips** [spm/spm#14]
We encountered a weird issue with some basic fMRI designs and tracked the problem to some events being defined with a `NaN` value instead of a numeral value. This should NOT happen of course but it still occurred because of the way the `events.mat` file (with the `names`, `onsets` and `durations` variables) was automatically created from the experiment log-files recorded at the scanner[^1]. Then with 10's of subjects to process, everything was pipelined till the group-level analysis.

## Description
Now the problem is easy to reproduce with a "design only" fMRI model specification, so here is a simple example:
- regular model with 4 block events for 1 condition with onsets at `[15 50 85 120]`s and durations `[20 20 20 20]`s
  ![GLM_orig](https://github.com/spm/spm/assets/2011934/89e9322b-8390-4587-8663-e155e732f673)
- same model but the duration of the 3rd event is set to `NaN`, i.e. `[20 20 NaN 20]`s
  ![GLM_NaN](https://github.com/spm/spm/assets/2011934/dbd2a4d0-6267-49e6-872a-51e1b29f06a7)

Tracking how the duration values are employed, the weird behavior stems from [line 131 in `spm_get_ons.m`](https://github.com/spm/spm12/blob/main/spm_get_ons.m#L131)
````
tof       = max(tof,1);
````
where `tof` encodes the events offset (in microtime bins) and `tof = [ 314 594 NaN 1154]'`. The  `max(tof,1)` operation turns it into  `tof = [ 314 594 1 1154]'`, which leads to a stimulus function `sf`
````
sf =
   (1,1)       -1
 (153,1)        1
 (314,1)       -1
 (433,1)        1
 (594,1)       -1
 (713,1)        1
 (993,1)        1
(1154,1)       -1
````
then the stimulus time course looks like
![StimFunc_NaN](https://github.com/spm/spm/assets/2011934/9bd8944a-b271-440d-933d-d64b90442c0b)
because of the `-1` placed in the 1st time bin [^2].

## Solution?
Could there be some check on the duration value at some point during the creation of the GLM? 
This would have saved us, and maybe others?, some stress...

[^1]: when the subject in the scanner did not press any response button after the stimulus, there was no "button press" time and it ended up being read a `NaN`. 
[^2]: the correct `tof` would look like  `[ 314 594 874 1154]'` and there is a clean 1/-1 pattern in the `sf` variable.

**Comment by ChristophePhillips** [comment]
The batch to reproduce the issue is simply:
````
matlabbatch{1}.spm.stats.fmri_design.dir = {'C:\2_Data\SPM_test_GLM\glm_nan'};
matlabbatch{1}.spm.stats.fmri_design.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_design.timing.RT = 2;
matlabbatch{1}.spm.stats.fmri_design.timing.fmri_t = 16;
matlabbatch{1}.spm.stats.fmri_design.timing.fmri_t0 = 8;
matlabbatch{1}.spm.stats.fmri_design.sess.nscan = 80;
matlabbatch{1}.spm.stats.fmri_design.sess.cond.name = 'Block';
matlabbatch{1}.spm.stats.fmri_design.sess.cond.onset = [15
                                                        50
                                                        85
                                                        120];
matlabbatch{1}.spm.stats.fmri_design.sess.cond.duration = [20
                                                           20
                                                           NaN
                                                           20];
matlabbatch{1}.spm.stats.fmri_design.sess.cond.tmod = 0;
matlabbatch{1}.spm.stats.fmri_design.sess.cond.pmod = struct('name', {}, 'param', {}, 'poly', {});
matlabbatch{1}.spm.stats.fmri_design.sess.cond.orth = 1;
matlabbatch{1}.spm.stats.fmri_design.sess.multi = {''};
matlabbatch{1}.spm.stats.fmri_design.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_design.sess.multi_reg = {''};
matlabbatch{1}.spm.stats.fmri_design.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_design.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_design.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_design.volt = 1;
matlabbatch{1}.spm.stats.fmri_design.global = 'None';
matlabbatch{1}.spm.stats.fmri_design.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_design.cvi = 'AR(1)';
````

**Comment by gllmflndn** [comment]
Thanks @ChristophePhillips for the detailed report.

I would be of the opinion that SPM should fail at creating a design matrix and report an error if NaN values are found in the onsets or durations arrays. An alternative would be to ignore such trials but I think the user should be warned instead.

The change should be in `spm_get_ons.m` or `spm_run_fmri_spec.m`. I would go for `spm_run_fmri_spec.m`. What about adding the following [here](https://github.com/spm/spm12/blob/main/config/spm_run_fmri_spec.m#L241):
```
if any(isnan(U(j).ons)) || any(isnan(U(j).dur))
    error('Onsets or Durations contain NaN values.');
end
```
We could also possibly check parametric modulations.

**Comment by ChristophePhillips** [comment]
Thanks @gllmflndn.

I am also in favour of throwing an error when `NaN`'s are found in the parameters defining the GLM, incl. modulations, as these are clearly erroneous values. No preference about where to perform the test. 😃

**Comment by gllmflndn** [comment]
OK, thanks. I pushed a change checking parametric modulations as well.

If it works as expected with you, please close this issue as fixed.
