### ISSUE TITLE
Normalise

### ISSUE THREAD

**Issue by sam880805** [spm/spm#16]
Because of the requirements of the university, I need to know how Normalise: Write works. Can I find the code or function of Normalize: Write here? Also, I want to ask whether the Deformation Field is linear or non-linear? Thank you for your answers.

**Comment by gllmflndn** [comment]
Hi @sam880805

To find the code being executed when using the Normalise:Write module from the batch interface, you need to follow this path:

1. It starts from the [spm_cfg_norm](https://github.com/spm/spm/blob/main/config/spm_cfg_norm.m#L35) configuration file
2. which calls [spm_run_norm](https://github.com/spm/spm/blob/main/config/spm_run_norm.m#L76) when executing a batch
3. which calls [spm_deformations](https://github.com/spm/spm/blob/main/spm_deformations.m#L366) with a `pullback` procedure to create the warped images. You can find some comment about the `pullback` and `pushforward` procedures in [spm_cfg_deformations](https://github.com/spm/spm/blob/main/config/spm_cfg_deformations.m).
