### ISSUE TITLE
'sensor' struct not being updated when cropping MEEG object 

### ISSUE THREAD

**Issue by KasiaRu** [spm/spm#19]
Hello @tierneytim @vlitvak 

I am raising the issue as a formality after an in person chat with @tierneytim. Thank you in advance for your time. 

It seems that the function spm_eeg_crop() is not updating the 'sensors' structure in the new MEEG object following the cropping, even though other fields such as 'chanlabels' are updated for the Dnew (see screenshot below).*

I have used the spm_eeg_crop() to crop out 2 channels which switched off halfway through the OPM recording session (such that half of the blocks had the channels, whereas the other did not. It was necessary to remove that difference as otherwise it was not possible to merge the blocks from the same session due to size incompatibility of the MEEG objects of different blocks). 

Whilst channels and sensors are not linked in SPM and it would not usually be the problem, the lack of updating 'sensors' struct became a problem to me when trying to use spm_opm_hfc() (specific error:  error('data size ~= number of sensors with orientation information'));

This is because spm_opm_hfc() draws information from the 'sensors' struct (and there are subfields for sensors corresponding to the channels which no longer exist). 

I have overcame this problem by updating the 'sensor' struct separately, using code below**. An alternative was to first run the hfc and crop the channels just before merging. However, some 3D source localisation methods may require sensor information which could lead to recurrence of the problem if the 'sensors' is not updated. Let me know if the 'sensor' struct should not be updated as below, or otherwise a similar approach could be incorporated inside the spm_eeg_crop().

-------------------------------------------------------------------------------------------------------------------------
* from inside the spm_eeg_crop() where channel information is updated but I do not think sensors are 
![image](https://github.com/spm/spm/assets/93380165/09a82996-b800-49a2-b768-702bb543ee3f)

*updating the 'sensors' struct to no longer include the channels cropped out with spm_eeg_crop(), run after the cropping itself (please let me know in case there are errors). 

for block_counter = 1:length(block)
    cropped_channel_labels{block_counter} = D{block_counter}.chanlabels(indchantype(D{block_counter}, 'MEG'))';
    non_cropped_sensor_labels{block_counter} = sensors(D{block_counter}, 'MEG').label;
    % define indices of sensors consistent with the cropped list of
    % channels (i.e., do not include indices of the cropped sensors)
    ind{block_counter} = find(contains(non_cropped_sensor_labels{block_counter},cropped_channel_labels{block_counter}));
    grad = D{block_counter}.sensors('MEG');
    gradnew = grad;
    gradnew.chanori = grad.chanori(ind{block_counter},:);
    gradnew.chanpos = grad.chanpos(ind{block_counter},:);
    gradnew.chantype = grad.chantype(ind{block_counter},:);
    gradnew.chanunit = grad.chanunit(ind{block_counter},:);
    gradnew.coilori = grad.coilori(ind{block_counter},:);
    gradnew.label = grad.label(ind{block_counter},:);
    gradnew.coilpos = grad.coilpos(ind{block_counter},:);
     % change size in both dimensions for .tra
    gradnew.tra = grad.tra(ind{block_counter},ind{block_counter});
    D{block_counter} = sensors(D{block_counter}, 'MEG', gradnew);
    save(D{block_counter});
end

**Comment by tierneytim** [comment]
Hi Kasia, thanks for reporting this. 

I can certainly change the HFC code to be based on channels as opposed to the  'sensors' struct. Unless @vlitvak  thinks that spm_eeg_crop should update the sensor's structure.  @vlitvak why does spm_eeg_crop not update the  'sensors' struct

**Comment by vlitvak** [comment]
As Kasia said, this is not usually necessary because it's enough for the data channels to be a subset of the sensor channels. There can be other situations when there are more channels in the sens struct than in the data, this is not enforced in the code. If this now causes a problem, it could possibly be added. Or alternatively the fix could be when merging or averaging to make it more generic.

Vladimir

**Comment by tierneytim** [comment]
> it's enough for the data channels to be a subset of the sensor channels

 if this is the case I will edit the HFC code to take information from the channels first. No changes to merging or averaging required. 

Will update when implemented.

**Comment by vlitvak** [comment]
Source reconstruction uses the rows in the lead field that correspond to the channels present in the data so it's not a problem. In cryogenic MEG  there are e.g. reference sensors that are almost never in the data. Also if you convert only a subset of channels it doesn't truncate the sens struct. I will put on my to-do list to update merging and averaging as this is a crash that could potentially be avoided. But if you are managing for now with Tim's fix I won't make it high priority.

**Comment by tierneytim** [comment]
Hi Kasia, 

Update applied, let me know if it works for you and I will close the issue

**Comment by tierneytim** [comment]
And thank you @KasiaRu for reporting. Please raise any further issues you encounter here as well
