### ISSUE TITLE
Question about first level analysis

### ISSUE THREAD

**Issue by KerenKasten** [spm/spm#24]
Hello, I'm Keren, a doctoral student conducting my first MRI scans and using SPM. I've encountered an issue and would appreciate some help. My motor task involves two conditions: in the first condition, the subject needs to reach a stimulus at a fixed location, and in the second condition, the subject needs to reach with their finger to a stimulus at an unknown location. When comparing each condition to rest, I observe activity in expected areas like the motor and visual cortex. However, when I contrast the condition with the unknown location against the known one, I'm seeing activity in various brain regions, including the Ventricles. Does anyone have ideas why I am getting this result (which is consistent across most subjects)

. Does anyone know how I can add a condition in the SPM GUI that shows the contrast of activity in the first condition less activity in the second condition but only the positive betas? (I thought that perhaps the betas in both conditions are negative, leading to the display of brain activity in the ventricles)

**Comment by pzeidman** [comment]
Hi Keren
If you specify a t-contrast, such as [1 -1], then this is equivalent to calculating beta1 minus beta2. SPM will only show positive effects on the brain plots. Whereas, if you specify an f-contrast, you will see any effects - positive or negative. So in your case, you need a t-contrast. 

The interpretation of effects in the ventricles is more tricky. It is a common occurrence and doesn't necessarily invalidate your results in the cortex. Hopefully your other activations look sensible - in terms of the brain regions that were recruited by the task. The only way to investigate the meaning of the ventricular activations would be to include regressors in the GLM expressing different hypotheses - e.g., head movement, breathing, or other physiological measures. At a minimum, I'd suggest always include head movement regressors.

Best 
Peter
PS we do intend to transition support to Github in future, but in the meantime you may get a faster and more comprehensive response on the SPM mailing list - which you can join via https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=spm
