### ISSUE TITLE
Error using spm_opm_create with the dataset of the tutorial "OPM SENSOR level:Evoked response"

### ISSUE THREAD

**Issue by FannyGrosselin** [spm/spm#29]
Dear all, 
I am trying to follow this tutorial [https://www.fil.ion.ucl.ac.uk/spm/docs/tutorials/opm/evoked/] with the provided dataset (https://www.fil.ion.ucl.ac.uk/spm/data/opm/opm-tutorial.zip). 
When I run the first lines of the tutorial: 
```
S = [];
S.data ='OPM_meg_001.cMEG';
S.positions= 'OPM_HelmConfig.tsv';
D = spm_opm_create(S);
```

I obtain the following error: 
```
SPM12: spm_opm_create                              10:25:08 - 01/07/2024
========================================================================
Warning: Cerca magnetics data currently requires separate coregistration and forward modelling 
Error using spm_opm_create (line 109)
A valid dataset or file was not supplied

Error in test_amm (line 13)
D = spm_opm_create(S);
```

By exploring a bit the error, in spm_opm_create.m, the code doesn't succeed to apply `fsize = finfo.bytes` in the function  read_cMEG_data of spm_opm_create.m.
Indeed, when I display finfo, I obtain: 
```
finfo = 

  0×1 empty struct array with fields:

    name
    folder
    date
    bytes
    isdir
    datenum
```

Matlab version used: MATLAB R2021b
SPM version used: SPM/12, main branch of the 29 June 2024, which may correspond to this commit a169eb951b45a2162c06a5febdb4004980eab356

I hope you can help me. 

Thanks

Fanny

**Comment by FannyGrosselin** [comment]
Hi Tim, 

Thanks for your responsiveness. 
I was running the code from matlab folder after having add the path of the dataset folder in the "Set path" window of matlab. 
Since your message, I have directly add the path in the code that call spm codes by using addpath(genpath('....')) pointing to dataset folder and to spm folder. I obtain same problem.
I am working on Linux, do you think the problem can come from this? Also to download spm I have used Git batch command by cloning the repo, maybe it would be preferable to download the zip folder?

**Comment by tierneytim** [comment]
Hi, 

We test on the latest version of ubuntu so if you are using that then that shouldn't be an issue, but if you are using a different distribution it is not impossible that the `dir` function does not work.  Using the git command vs downloading the zip folder shouldn't make a difference either. You should also never need to use genpath as spm should sort this out for you. Try the following 

```
addpath('path\to\GitHub\spm')
spm('defaults','eeg');
cd 'path\to\tutorial'

S = [];
S.data ='OPM_meg_001.cMEG';
S.positions= 'OPM_HelmConfig.tsv';
D = spm_opm_create(S);

```

**Comment by FannyGrosselin** [comment]
Hi, 

By running the code you have given, I obtain same error : 
```
Error using spm_opm_create (line 109)
A valid dataset or file was not supplied

Error in test (line 8)
D = spm_opm_create(S);
```

My operating system is the following: Rocky Linux 8.10
Have you some advice to test the functionnality of dir function?

**Comment by tierneytim** [comment]
you can check with the following 

```
finfo = dir('fullpath\to\data\OPM_meg_001.cMEG');
finfo

```

you can do this for any file. so it is worth checking on another file in your working directory as well. on my machine finfo is empty when the filepath is misspecified.

**Comment by FannyGrosselin** [comment]
Hi Tim, 

I have check with the code in your latest message and I realize that I stupidly missed a directory in the path.... So all is ok now with this code your sent to me yesterday:
```
addpath('path\to\GitHub\spm')
spm('defaults','eeg');
cd 'path\to\tutorial'

S = [];
S.data ='OPM_meg_001.cMEG';
S.positions= 'OPM_HelmConfig.tsv';
D = spm_opm_create(S);
```
Very sorry for the disturbing and thank you for your time.

Have a nice day

Best
