### ISSUE TITLE
Bizarre issue on MATLAB 2023b, macos-13

### ISSUE THREAD

**Issue by pzeidman** [spm/spm#31]
I am tackling a weird code bug that is specific to Matlab 2023b on Mac. I am close to concluding it’s a Matlab issue. Any thoughts would be appreciated.

### Symptoms
An SPM unit test is failing (test_spm_dcm_bmr_all/test_bmr_all) on MATLAB 2023b, macos-13. It passes on all other operating systems and earlier Matlab versions.

### Diagnosis
In spm_dcm_bmr.m, we have a variable named Pk, which is a [2 x 6] vector of type double: 

```
      0.0264    0.0312    0.0312    0.0243    0.0312    0.0312
      0.0049    0.0000    0.0000    0.0069    0.0000    0.0001
```

The following code (spm_dcm_bmr:335) should return the values in the first row of Pk as a fraction of the total over rows:

`Pk    = Pk(1,:)./sum(Pk);`

However, the resulting value of Pk is incorrectly all zeros:

`0     0     0     0     0     0`

Most bizarrely, if we instead perform the above calculation without assigning it to variable Pk:

`disp(Pk(1,:)./sum(Pk));`

Then we get the correct result:

`0.8445    1.0000    1.0000    0.7781    1.0000    0.9971`

Attempting to re-create the problem in a standalone unit test worked perfectly, failing to reproduce the problem (test_spm_dcm_bmr_all/test_divide).

Any ideas? 

Relevant files:

- Line 335 of spm_dcm_bmr_all.m https://github.com/spm/spm/blob/main/spm_dcm_bmr_all.m 
- test_spm_dcm_bmr_all https://github.com/spm/spm/blob/main/tests/test_spm_dcm_bmr_all.m 
- Test results: https://github.com/spm/spm/actions/runs/9804659564/job/27072829745 

Best
Peter

**Comment by georgeoneill** [comment]
Hi Peter, incredibly weird issue. Do we know if this persists in 2024a at all?

**Comment by pzeidman** [comment]
Thanks George. Good question, but I don't know the answer - currently our tests on Github only run up to Matlab 2023b. (The Mac Mini we have here for testing runs Matlab 2023b Mac-OS 14, and the problem doesn't occur. Github uses Mac-OS 13, so maybe the problem also depends on OS...)

**Comment by georgeoneill** [comment]
We also have the incredibly cursed notion that this might also be architecture specific too. Do we know if GiotHub is Interl or ARM?

**Comment by pzeidman** [comment]
Nice suggestion to check - we're currently using the "macos-13" image, which is x86 based [1]. Whereas, we could try macos-14 (or macos-latest), which is Arm. 

[1] https://www.reddit.com/r/github/comments/1cjiat4/is_github_actions_macoslatest_now_only_armbased/

**Comment by pzeidman** [comment]
Problem solved. Pre-allocating the variable (Pk) resolved the issue, which make me think it's a MATLAB and/or Github bug. I'll report it to Mathworks and share any feedback they give. Here's a reproducible test case without pre-allocation:

```
function test_divide(testCase)

% Confirm that variable Pk does not exist. Outputs: 'Pk' not found.
which Pk

% Now assign some values to it
Pk(1,:) =  [0.0264    0.0312    0.0312    0.0243    0.0312    0.0312];
Pk(2,:) =  [0.0049    0.0000    0.0000    0.0069    0.0000    0.0001];
   
% Divide the first row by the sum over rows
Pk = Pk(1,:)./sum(Pk);

% Confirm it's NOT the case that all values are zero (pathological)
testCase.assertTrue(~all(abs(Pk) < 0.001));
```
The incorrect result is a value of [0 0 0 0 0 0] for variable Pk on Mac + MATLAB 2019a. All other platforms give the correct value: Pk = [0.8445    1.0000    1.0000    0.7781    1.0000    0.9971].
