### ISSUE TITLE
cMEG file import error

### ISSUE THREAD

**Issue by Fololo** [spm/spm#38]
Hi all, 

We were trying to run the [SPM tutorial on OPM data](https://www.fil.ion.ucl.ac.uk/spm/docs/tutorials/opm/evoked/) but was not able to import the raw data using ``spm_opm_create(S)``. We got the following error: 

```
SPM12: spm_opm_create                              17:57:53 - 14/10/2024
========================================================================
Error using reshape
Size arguments must be real integers.

Error in spm_opm_create (line 112)
    S.data = reshape(S.data,nc,numel(S.data)/nc);

Error in tutorial (line 5)
D = spm_opm_create(S);
```

Has anyone encountered this issue before?

**Comment by tierneytim** [comment]
Hi Florian,

This usually means that there is an issue with the 'OPM_channels.tsv' file or it hasn't been read correctly.

Could you post the exact code you used and a screenshot of the current working directory to help isolate the problem. The following works find on my computer. 

```
cd 'C:\Users\ttierney\path\to\tutorial'
S = [];
S.data ='OPM_meg_001.cMEG';
S.positions= 'OPM_HelmConfig.tsv';
S.channels = 'OPM_channels.tsv';
D = spm_opm_create(S); 
```

The specification of the channels argument shouldn't be necessary if you have all the right files.

**Comment by Fololo** [comment]
Hi @tierneytim, 

thanks for you quick response and sure! 

The code I am running is simply the first block in the tutorial, so 

```Matlab 
S = [];
S.data = '/Users/fschoenleitn/Desktop/tutorial/OPM_meg_001.cMEG';
S.positions = '/Users/fschoenleitn/Desktop/tutorial/OPM_HelmConfig.tsv';
D = spm_opm_create(S);
```

All files are placed on my desktop, which is also the working directory: 

```Matlab 
>> pwd

ans =

    '/Users/fschoenleitn/Desktop/tutorial'
```

The directory structure is: 
```
tutorial/
├── head.obj
└── headhelmet.obj
└── OPM_channels.tsv
└── OPM_HelmetConfig.tsv
└── OPM_meg.json
└── OPM_meg_001.cMEG
└── OPM_SessionInfo.txt
└── tutorial.m

```

I also tried to pass the channels argument explicitly by 

```Matlab 
S = [];
S.data ='/Users/fschoenleitn/Desktop/tutorial/OPM_meg_001.cMEG';
S.positions = '/Users/fschoenleitn/Desktop/tutorial/OPM_HelmConfig.tsv';
S.channels = 'OPM_channels.tsv';
D = spm_opm_create(S);
```

but that didn't solve the problem.

**Comment by tierneytim** [comment]
hmm, that's a pain. 

Some questions that will hopefully point us in the right direction

1. Are you running the latest version of SPM from this GitHub repository? I'm not sure I recognise that code line (think it might be from an earlier/different version of code)
2. Could you post of a screenshot of the channels file open in some text editor?

**Comment by Fololo** [comment]
So we figured it out.

We were having an old version of the function ``spm_opm_create()`` which was updated three months ago by Steph ([see this bugfix](https://github.com/spm/spm/commit/367453ab96e69bd0fa925f03f0411bec9f97d537)). 

However, if you [download SPM 12 manually from the website](https://www.fil.ion.ucl.ac.uk/spm/download/restricted/eldorado/spm12.zip) it is shipped with the old function. Maybe it would be worth changing this?

**Comment by tierneytim** [comment]
Brilliant, 

Glad it is solved. At least for the OPM code the only place you should get the code from is GitHub. I'll make sure to update documentation to reflect this.

Thanks for the input
