### ISSUE TITLE
spm_mesh_ray_triangle not compiled

### ISSUE THREAD

**Issue by georgeoneill** [spm/spm#49]
It appears spm_mesh_ray_triangle (which spm_mesh_voxelise is dependent on) is compiled for Linux and Apple Sillicon by not Apple Intel or Windows 

![image](https://github.com/user-attachments/assets/b6f75815-28de-43a2-95f7-2489b1483c25)

**Comment by korbinian90** [comment]
Files pushed to main (29952b8bedbff025d65560cd7dae3e5f78537f41)
I triggered the [compile mex](https://github.com/spm/spm/actions/workflows/compile_mex.yml) action and added the two missing files ([action docs](https://www.fil.ion.ucl.ac.uk/spm/docs/development/compilation/#automatic-recompilation-on-github-actions))
This seem to be the only missing mex files

I hope this solves it!

**Comment by georgeoneill** [comment]
Thank you @korbinian90, that appears to have fixed it!
