### ISSUE TITLE
Bug in DICOM import: MRScaleSlope/MRScaleIntercept with more than 1 value

### ISSUE THREAD

**Issue by ftadel** [spm/spm#5]
A user reported this bug on the Brainstorm forum:
https://neuroimage.usc.edu/forums/t/import-mri-error/37412

After testing with the DICOM folder the user provided, I found that MRScaleSlope/MRScaleIntercept have more than one value.
Debugger at line 625 of spm_dicom_convert shows:

```
K>> Headers{1}.MRScaleSlope
ans =
   147   109    39    59

K>> Headers{1}.MRScaleIntercept
ans =
     0     0     0     0
```

This is not handled in the function, it causes the following error:

```
** Error: Line 625:   / 
** Matrix dimensions must agree.
** 
** Call stack:
** >spm_dicom_convert.m>WriteVolume at 625
** >spm_dicom_convert.m>ConvertStandard at 246
** >spm_dicom_convert.m at 72
```

@gllmflndn I'll send you the DICOM folder by email (this is not public data).

Related to this commit:
https://github.com/spm/spm/commit/5ea021bdcac79d6dc0a15619010e9258189b39ed

**Comment by gllmflndn** [comment]
Thank you @ftadel for the bug report and the dataset. @JohnAshburner fixed this in [f90343fc0d92c4f8ed489ff0bb943f018cfe4fe8](https://github.com/spm/spm/commit/4de61367cb0f1db32f63fcc9810d185a5f6f5d79)
